module.exports = {
  cryptor: {
    root: [
      {
        parent:"/",
        name:"loader",
        type:"dir",
        children: [ 
          {
            parent:"/loader/",
            name:"loader.props",
            type:"file"
          },
          {
            parent:"/loader/",
            name:"loader.cpp",
            type:"file"
          },
          {
            parent:"/loader/",
            name:"loader-release.props",
            type:"file"
          },
          {
            parent:"/loader/",
            name:"loader.vcxproj",
            type:"file"
          },
          {
            parent:"/loader/",
            name:"loader.vcxproj.filters",
            type:"file"
          },
          {
            parent:"/loader/",
            name:"malware_external.h",
            type:"file"
          },
        ]
      }, 
      {
        parent:"root",
        name:"cryptor_and_loader",
        type:"dir",
        children:[
          {
            parent:"/cryptor_and_loader/",
            name:"cryptor.cpp",
            type:"file"
          },
          {
            parent:"/cryptor_and_loader/",
            name:"cryptor_and_loader.vcxproj",
            type:"file"
          },
          {
            parent:"/cryptor_and_loader/",
            name:"cryptor_and_loader.vcxproj.filters",
            type:"file"
          },
        ]
      },
      {
        parent:"/",
        name:"README.md",
        type:"file"
      }
    ]
  },
  proxy: {
    root:[
      {
        parent:"/",
        name:"squid_files",
        type:"dir",
        children: [
          {
            parent:"/squid_files/",
            name:"rewrite.py",
            type:"file",
          },
          {
            parent:"/squid_files/",
            name:"squid.conf",
            type:"file",
          }
        ]
      },
      {
        parent:"/",
        name:"models",
        type:"dir",
        children: [
          {
            parent:"/models/",
            name:"formsubmit.js",
            type:"file",
          },
          {
            parent:"/models/",
            name:"pagevisit.js",
            type:"file",
          },
        ]
      },
      {
        parent:"/",
        name:"views",
        type:"dir",
        children: [
          {
            parent:"/views/",
            name:"pages",
            type:"dir",
            children:[
              {
                parent:"/views/pages/",
                name:"adminforms.ejs",
                type:"file",
              },
              {
                parent:"/views/pages/",
                name:"adminvisits.ejs",
                type:"file",
              },
            ]
          },
          {
            parent:"/views/",
            name:"partials",
            type:"dir",
            children:[
              {
                parent:"/views/partials/",
                name:"head.ejs",
                type:"file",
              },
            ]
          },
        ]
      },
      {
        parent:"/",
        name:"env_template",
        type:"file",
      },
      {
        parent:"/",
        name:"package.json",
        type:"file",
      },
      {
        parent:"/",
        name:"package-lock.json",
        type:"file",
      },
      {
        parent:"/",
        name:"malicious.ejs",
        type:"file",
      },
      {
        parent:"/",
        name:"server.js",
        type:"file",
      },
      {
        parent:"/",
        name:"package.json",
        type:"file",
      },
      {
        parent:"/",
        name:"README.md",
        type:"file",
      },
    ]
  }
}